server:
  port: 8888
spring:
  application:
    name: rodrigo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/secodigo/rodrigo-config-server.git
          username: secodigo
          password: ro009martins
          default-label: main
          search-paths:
          - 'greeting-service*'
         